name: Test

on:
  push:
  release:
    types:
      - created

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'

  dependencies:
    needs: setup
    runs-on: ubuntu-latest
    steps:
    - run: npm install -g yarn
    - run: yarn install

  test:
    needs: dependencies
    runs-on: ubuntu-latest
    steps:
    - run: yarn test
